#This code was written by Tobyn Branck and visualizes bestTrees generated by strainphlan4
#Specifically, it generates trees and annotates the tips so that we can show strain-similarity 
#across hosts.
library("ggplot2")
library("grid")
library(tidyverse)
library(factoextra)
library(ade4)
library(FactoMineR)
library("plyr")
library("dbplyr")
library(ggbreak)
library(grid)
library(gtable)
library(gridExtra)
library(ggtree)

setwd("/Users/tobynbranck/Documents/pets_meta/")
source("/Users/tobynbranck/Documents/keep_SGB.R")

#bringing in metaphlan table simply for grepping taxonomy labels to annotation trees
metaphlan_table = as.data.frame(data.table::fread("/Users/tobynbranck/Documents/pets_meta/pets_metaphlan_v4_formatted_SGBtree.csv", header=T, check.names = F))
metaphlan_table$V1 = gsub("SP_","t_",metaphlan_table$V1)
rownames(metaphlan_table) = metaphlan_table$V1
metaphlan_table$V1 = NULL
metaphlan_table = keep_SGB(metaphlan_table)
metaphlan_table$taxa = rownames(metaphlan_table)
taxa_df = as.data.frame(metaphlan_table$taxa)
taxa_df$SGB = gsub(".*SGB","",taxa_df$`metaphlan_table$taxa`)
taxa_df$SGB = paste0("SGB",taxa_df$SGB,sep="")

dir<-"/Users/tobynbranck/Documents/pets_meta/bestTrees"
#get a list of all files with ".tre" in the name in your directory
files<-list.files(path=dir, pattern='.tre', full.names = TRUE)

for (file in files){
  name <- file
  tree = read.tree(name)
  metadata = as.data.frame(data.table::fread("/Users/tobynbranck/Documents/pets_meta/all_metadata_preformatted.csv", header=T, check.names = F))
  metadata = metadata[,c('sample_id_metaphlan','species')]
  names(metadata) = c('sample','host')
  metadata$sample = paste0(metadata$sample,'_bowtie2')
  metadata = metadata[metadata$sample %in% tree$tip.label,]
  metadata = metadata[match(tree$tip.label, metadata$sample),]
  tree$tip.label = metadata$host
  
  groupInfo = split(tree$tip.label, gsub("_\\w+", "", tree$tip.label))
  tree = groupOTU(tree,groupInfo)
  
  # get taxonomy for SGB to label plot and save appropriately
  name = gsub("/Users/tobynbranck/Documents/pets_meta/bestTrees/RAxML_bestTree.t__","",name)
  name = gsub(".StrainPhlAn4.tre","",name)
  taxa_name = taxa_df$`metaphlan_table$taxa`[taxa_df$SGB == name]
  print(taxa_name)
  vis = ggtree(tree,branch.length = 'none',layout = 'circular',aes(color=group,alpha=.5)) +   
    scale_color_manual(values=c(cat = "indianred",dog= "#E69F00", human = "#56B4E9",reference="black")) +
    ggtitle(sprintf("%s",taxa_name))
  
  cairo_pdf(sprintf("/Users/tobynbranck/Documents/pets_meta/strainphlan_trees_output/%s_treeVis.pdf",taxa_name))
  print(ggtree(tree,branch.length = 'none',layout = 'circular',aes(color=group)) +   
    scale_color_manual(values=c(cat = "indianred",dog= "#E69F00", human = "#56B4E9",reference="black")) +
    scale_size_manual(values=c(1, .1)) +
    ggtitle(sprintf("%s",taxa_name)))
  dev.off()
}