#This code was written by Tobyn Branck and visualizes bestTrees generated by strainphlan4
#Specifically, it generates trees and annotates the tips so that we can show strain-similarity 
#across hosts.
library("ggplot2")
library("grid")
library(tidyverse)
library(factoextra)
library(ade4)
library(FactoMineR)
library("plyr")
library("dbplyr")
library(ggbreak)
library(grid)
library(gtable)
library(gridExtra)
library(ggtree)

#set the file path for input & output files
input_dir = file.path("/home/tobynb/shared-folder/tbranck/Pets_pooled_analysis/inputs")
output_dir = file.path("/home/tobynb/shared-folder/tbranck/Pets_pooled_analysis/outputs")
source("/home/tobynb/shared-folder/tbranck/keep_SGB.R")

#bringing in metaphlan table simply for grepping taxonomy labels to annotation trees
metaphlan_table = as.data.frame(data.table::fread(file.path(output_dir,"pets_metaphlan_v4_formatted_SGBtree_Jun23tax.csv"), header=T, check.names = F))
metaphlan_table$V1 = gsub("SP_","t_",metaphlan_table$V1)
rownames(metaphlan_table) = metaphlan_table$V1
metaphlan_table$V1 = NULL
metaphlan_table = keep_SGB(metaphlan_table)
metaphlan_table$taxa = rownames(metaphlan_table)
taxa_df = as.data.frame(metaphlan_table$taxa)
taxa_df$SGB = gsub(".*SGB","",taxa_df$`metaphlan_table$taxa`)
taxa_df$SGB = paste0("SGB",taxa_df$SGB,sep="")

dir<-file.path(input_dir,"bestTrees")

#get a list of all files with ".tre" in the name in your directory
files<-list.files(path=dir, pattern='.tre', full.names = TRUE)

#loops through each of the .tre files and visualizes the individual SGB trees using the ggtree package. Tips are colored by host species.
for (file in files){
  name <- file
  print(name)
  tree = read.tree(name)
  tree$tip.label = gsub(" ","_",tree$tip.label)
  metadata = as.data.frame(data.table::fread(file.path(input_dir,"metadata.csv"), header=T, check.names = F))
  metadata = metadata[,c('sample_id_metaphlan','species','study_readable')]
  madagascar_samp_mapping = as.data.frame(data.table::fread(file.path(input_dir,"madagascar_SraRunTable.txt"), header=T, check.names = F))
  metadata$sample_id_metaphlan[metadata$study_readable=='Madagascar'] = madagascar_samp_mapping$Run[match(metadata$sample_id_metaphlan,madagascar_samp_mapping$'Library Name')][239:350]
  metadata$species[metadata$study_readable=='HMP1-II'] <- 'HMP1-II'
  metadata$species[metadata$study_readable=='Madagascar'] <- 'Madagascar'
  metadata$study_readable = NULL
  names(metadata) = c('sample','host')
  print(head(metadata))
  metadata$sample = paste0(metadata$sample,'_bowtie2')
  metadata = metadata[metadata$sample %in% tree$tip.label,]
  metadata = metadata[match(tree$tip.label, metadata$sample),]
  tree$tip.label = metadata$host
  print(tree$tip.label)
  
  groupInfo = split(tree$tip.label, gsub("_\\w+", "", tree$tip.label))
  tree = groupOTU(tree,groupInfo)
  print(tree$tip.label)
  # get taxonomy for SGB to label plot and save appropriately
  name = gsub(file.path(input_dir,"bestTrees/RAxML_bestTree.t__"),"",name)
  name = gsub(".StrainPhlAn4.tre","",name)
  print(name)
  name = gsub("_group","",name)
  print(name)
  taxa_name = taxa_df$`metaphlan_table$taxa`[taxa_df$SGB == name] #pulls in name from mpa table (maps the SGBXXXX to classification in mpa table)
  print(taxa_name)
  vis = ggtree(tree,branch.length = 'none',layout = 'circular',aes(color=group,alpha=.5)) +   
    scale_color_manual(values=c(cat = "indianred",dog= "#E69F00", "HMP1-II" = "#56B4E9","Madagascar"="#0f3b50")) +
    ggtitle(sprintf("%s",taxa_name))
  print(vis)
  cairo_pdf(sprintf("/home/tobynb/shared-folder/tbranck/Pets_pooled_analysis/outputs/strainphlan_trees_output/%s_treeVis.pdf",taxa_name))
  print(ggtree(tree,branch.length = 'none',layout = 'circular',aes(color=group)) +
    scale_color_manual(values=c(cat = "indianred",dog= "#E69F00", "HMP1-II" = "#56B4E9","Madagascar"="#0f3b50")) +
    scale_size_manual(values=c(1, .1)) +
    ggtitle(sprintf("%s",taxa_name)))
  dev.off()
}
